#page title
page_title                                : WeatherAlerts Official Website                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://github.com/ExoticDG/WeatherAlerts/releases                                          # Enter Google Play Store URL.
presskit_download_link                    : https://github.com/ExoticDG/WeatherAlerts/releases                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
github_download_link                      : https://github.com/ExoticDG/WeatherAlerts/releases                                                               # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ic_launcher_round.png
app_name                                  : WeatherAlerts
app_price                                 : "Price : Free!"
app_description                           : The app that prioritizes your safety and security over profit.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ExoticDarknessGaming                                
your_link                                 : https://exoticdg.github.io                    
your_city                                 :                               
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : ExoticDG
youtube_tag                               : "@ExoticDarknessGaming"
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Smart Location Tracking
    description                           : Tracks location through built in Android APIs to consonantly provide accurate data for your location.
    fontawesome_icon_name                 : star
    
  - title                                 : Accurate Data
    description                           : Provides accurate data for US citizens through National Weather Service API's
    fontawesome_icon_name                 : star

  - title                                 : Alert Method Variety
    description                           : A large variety of alteration methods using the various Android API's provided by Google LLC such as System-Overlay alerts and custom vibration patterns for life-threatening alerts.
    fontawesome_icon_name                 : star

  - title                                 : Fast Alerts
    description                           : With a combination of Google Firebase, Google Cloud, and government API's you will be notified of any on-coming disaster ASAP.
    fontawesome_icon_name                 : star

  - title                                 : Backwards Compatible
    description                           : This app has been tested on devices all the way back to the Google Pixel 2 and Android 11, ensuring compatibility with a large variety of devices.
    fontawesome_icon_name                 : star
  
  - title                                 : Indie-Dev
    description                           : No big corporation behind this. Just a solo dev who had a problem with the slowness, inaccuracies, and trustworthiness of other applications.
    fontawesome_icon_name                 : star

  - title                                 : Available Code
    description                           : Don't trust this app? Thats fine! I didn't trust the others with my life. I have made all of the code for my application available on GitHub under a All Rights Reserved license. Feel free to look at it!
    fontawesome_icon_name                 : star

  - title                                 : TITLE
    description                           : DESCRIPTION
    fontawesome_icon_name                 : star


  - title                                 : TITLE
    description                           : DESCRIPTION
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
